version: '3.7'
services:
    database:
        image: gftubs/mysql:v1
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        build:
            context: ./Docker/mysql
            dockerfile: Dockerfile
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: TestGfTUBS@2021
            MYSQL_USER: gftubs
            MYSQL_PASSWORD: UBS@2021
            MYSQL_DATABASE: lacd
        volumes:
            - ./Database/MAIN:/var/lib/mysql
            - ./Docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/source/mysqld.cnf
        ports:
            - "3310:3306"
        networks:
            - gft-ubs-network
    backend:
        image: gftubs/java:v1
        command: mvn clean spring-boot:run
        restart: on-failure
        build: ./Docker/java
        working_dir: /Backend
        environment:
            TZ: America/Sao_Paulo
            SPRING_BOOT_ENVIRONMENT: Production
            SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/receba_main
            SPRING_DATASOURCE_USERNAME: receba
            SPRING_DATASOURCE_PASSWORD: Receba2021@Main
        volumes:
            - ./Backend:/Backend
            - ~/.m2:/root/.m2
        ports:
            - "8080:8080"
        expose:
            - "8080"
        depends_on:
            - database
        networks:
            - gft-ubs-network
networks:
    gft-ubs-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.21.238.0/24
